spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.44/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.31.44
    port: 6379
server:
  context-path: /sell
  
  
wechat:
  mpAppId: wxc80aa306ca075013
  mpAppSecret: 2eb4bf23f5389da83a48870495496983
  mchId: 1394130302
  mchKey: c976503d34ca432c601361f969fd8d66   
  keyPath: C:\Users\gxl17\Documents\workspaces\IdeaProjects\sell\src\main\resources\static\h5.p12
  notifyUrl: http://gxl.mynatapp.cc/sell/notify   # 正式上线需要修改为  http://gxl.mynatapp.cc/sell/pay/notify
  openAppId: 
  openSecret: 
  
projectUrl:
  wechatMpAuthorize: http://gxl.mynatapp.cc
  wechatOpenAuthorize: http://gxl.mynatapp.cc
  sell: http://gxl.mynatapp.cc
  
  
    